### ISSUE TITLE
Mining nodes

### ISSUE THREAD

**Issue by 83Nitroxyde** [stormrage-project/stormrage-1.12-bugtracker#126]
Hi,

I have been trying to leveling up my mining recently, and i noticed that the node spawns are alot less then what they are suppose to be.

Arathi highlands for example, holds 3 iron node after a full circle off the zone.

This seems abit on the low side from my past experiance's there.

**Comment by stormrage-project** [comment]
Preparations for the new mining spawn system are made. Now we need to populate the pools with nodes.

**Comment by stormrage-project** [comment]
Ore nodes are completely overhauled now. Next step is to link them to our pool and subpool system

**Comment by stormrage-project** [comment]
The implementation of the ore pool system is finished now. This issue is fixed now.
