### ISSUE TITLE
Clearcasting Druid

### ISSUE THREAD

**Issue by Kuzmin1994** [stormrage-project/stormrage-1.12-bugtracker#132]
Omen of Clarity http://db.vanillagaming.org/?spell=16864 bugged. If u use Faerie Fire http://db.vanillagaming.org/?spell=16857 or Prowl http://db.vanillagaming.org/?spell=5215 - abilities that do not require cost, Clearcasting state will be dispell, similar abilities should not deprive this effect. Also, the use of healing spells require mana, when the ability triggered.

**Comment by stormrage-project** [comment]
Fixed.

**Comment by ROKB** [comment]
can you show me change log url?
