### ISSUE TITLE
Mobs with fear... 

### ISSUE THREAD

**Issue by monkfish** [stormrage-project/stormrage-1.12-bugtracker#141]
first of all, i dont know if player fears do the same to other players or mobs but this is the bug i found;
im a shaman so i have tremor totem, but every time the fear breaks the character keeps running in the same direction and you basically lose the control of your character for 3 seconds and you dont even have fear in you... that shit killed me so many times... running straight to other mobs and shit. 
if that was scripted in the same instant the fear is breaked you get the control of your chatacter. but here the fear breaks and you are still out of control.
when you are running straight without control if you spam mouse movement and keyboard movement maybe you break that "out of control state" it some times work. but not always, so its a pain in the ass to fight fearing mobs.
pls fix this ASAP, game breaking bug

**Comment by stormrage-project** [comment]
Fixed.
