### ISSUE TITLE
warrior: charge / intercept skill

### ISSUE THREAD

**Issue by rotterz** [stormrage-project/stormrage-1.12-bugtracker#154]
i notice that on alot of servers everyone has an issue with charge or intercept. i understand the terrain bugging is hard to fix. but its more annoying when the ability doesnt even put you in melee range of anything. you still have to run forward to get to the target. in pve ppl dont notice this as much because npc monsters run towards you as you attack. but thinking on a bigger picture, what about pvp ? your chasing someone down. you charge, and cant even hamstring. or out of range for other abilities

**Comment by cabfever** [comment]
As @cardk already said: This is working blizzlike. We could talk about improving it though in the future.
