### ISSUE TITLE
Scarlet Monastary level requirement

### ISSUE THREAD

**Issue by cardk** [stormrage-project/stormrage-1.12-bugtracker#164]
It says requires level 35 to enter, however that was never the case in 1.12.1, as many 29 twinks used the dagger from 1st boss SM GY. The original level requirement to enter was 21 or 25.

Regards Kish

**Comment by stormrage-project** [comment]
Graveyard entrance is set to level 29.
Library entrance is set to level 31.
Armory entrance is set to level 33.
Cathedral entrance is set to level 35.
