### ISSUE TITLE
Warlock : Improved Shadowbolt

### ISSUE THREAD

**Issue by fixthisbug** [stormrage-project/stormrage-1.12-bugtracker#170]
Spell.
Your Shadow Bolt critical strikes increase Shadow damage to the target by 20% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12sec.

The debuff doestn work correctly -  the debuff reduce on every spell (like immolate / wand hit)
Would be nice if you can fix it, because its pretty significant for warlocks

cya :)

**Comment by stormrage-project** [comment]
Fixed.

**Comment by ROKB** [comment]
i cant find fix source.. please show me change source..
