### ISSUE TITLE
Warlock Spell - Corruption

### ISSUE THREAD

**Issue by Necrolock** [stormrage-project/stormrage-1.12-bugtracker#171]
Information about spell : Corrupts the target, causing 732 to 738 Shadow damage over 18sec. (Rank 6) So the dot deals 122 shadow damage every 3 sec without any  spell damage you have.
So the bug is, this spell deals same damage even if you have spell damage. Its like spell damage doesnt effect this skill.. Please fix it :p

**Comment by stormrage-project** [comment]
This should be fixed now.
