### ISSUE TITLE
Warlock - Spellstone

### ISSUE THREAD

**Issue by Necrolock** [stormrage-project/stormrage-1.12-bugtracker#172]
Spellstone can be used even if you dont have any dispellable thing on you.
Proof : http://www.youtube.com/watch?v=NZIg4OZlA-4   (7:13)

**Comment by stormrage-project** [comment]
This is the same issue as Shield Slam for warriors. We are working on this.

**Comment by stormrage-project** [comment]
This should be fixed now.
