### ISSUE TITLE
Drop Rate: Essence of undead

### ISSUE THREAD

**Issue by twiztidlily** [stormrage-project/stormrage-1.12-bugtracker#174]
Have been farming for it in Winter spring from Anguished Highborne and Suffering Highborne. Suppose to be a drop rate of 7 an 5/6 but have not had a drop from either. Farming last 3 days.

**Comment by cabfever** [comment]
As you can see here: http://db.vanillagaming.org/?item=12808 Essence of Undeath has a pretty low drop rate from creatures outside. So this is blizzlike.
