### ISSUE TITLE
Warlock Spell - Health Funnel

### ISSUE THREAD

**Issue by Necrolock** [stormrage-project/stormrage-1.12-bugtracker#195]
Spell power doesnt affect Health Funnel.

**Comment by stormrage-project** [comment]
Could you please retest it, since we overworked the spelldamage system?

**Comment by Vulturous** [comment]
Spelldamage properly applies to Health Funnel now. Thank you :)

**Comment by stormrage-project** [comment]
Spellpower does now affect Health Funnel.
