### ISSUE TITLE
Crowd control bugged in pvp

### ISSUE THREAD

**Issue by Rockmaster1** [stormrage-project/stormrage-1.12-bugtracker#199]
Like you probably know all major crowd controlls like: sheep, fear, sap, snares, slows ... have their full duration without any diminishing return when used on players.
This is a huge problem when pvping. Mages can sheep you for days and so on.
Warlock fear seems to have no chance of breaking from damage, and shares no dr as well.
This is really frustrating for all players who want to pvp. 
Please fix cc's and make them blizzlike!

**Comment by cabfever** [comment]
Added first implementation of heartbeat resist: http://forum.wow-vanilla.com/viewtopic.php?f=30&t=562#p1592
