### ISSUE TITLE
Felwood: Cleansing Night Dragon, Songflower, Windblossom, Whipper Root

### ISSUE THREAD

**Issue by Vulturous** [stormrage-project/stormrage-1.12-bugtracker#200]
According to the patch notes they were supposed to be fixed but they aren't. Last night I tried numerous times to loot the cleansed plants and did not get any Windblossom Berries, Whipper Root Tubers, Night Dragon's Breath, or the Songflower Serenade buff (+crit, +spell crit, +15 attributes). You could cleanse them before the patch and you can now, but that doesn't change that you still can't loot the _cleansed_ version of the plant after cleansing it which is the actual point. It's nice that the quest part was allegedly fixed (can't tell since I'm 60) but that's not the reason every self-respecting raider got the buff and some stacks of consumables from these back in Classic. Night Dragon is the only source of mana outside potions, since they are on the consumables timer, not the potion timer.

**Comment by stormrage-project** [comment]
Fixed.
