### ISSUE TITLE
Snare effects on pets

### ISSUE THREAD

**Issue by Vulturous** [stormrage-project/stormrage-1.12-bugtracker#204]
Snares like Hamstring, Tendon Rip, Crippling Poison etc. from PvE mobs don't work on some pets. Observed every day on my Voidwalker who cannot be snared (not dazed either btw) while he's on follow. He gets the debuffs but never slows down. This is true for when their master is mounted or on foot.

**Comment by Vulturous** [comment]
Pinned it down. Pets' movement speed on Stormrage is bound to the master's speed at all times, disregarding the pets' own debuffs. A hamstrung master's pet will move slowed even though the pet itself is not slowed. A non-slowed master's pet will not be slowed, even if it has a movement impairing effect on it.

**Comment by stormrage-project** [comment]
fixed.
