### ISSUE TITLE
Alt+F4ing in combat, especially pvp

### ISSUE THREAD

**Issue by Vulturous** [stormrage-project/stormrage-1.12-bugtracker#206]
If you hit alt+F4 on retail, your character remains in the game uncontrolled, until it gets timed out. That is, when out of pve combat. As we know on Stormrage you instantly disappear. Alliance has started to alt+F4 when they get attacked by a Horde player, thus making it next to impossible to get HKs. I would call this bug abuse.
Something needs to be done about that.

**Comment by stormrage-project** [comment]
Fixed.
