### ISSUE TITLE
Problem with learning Swordsmithing.

### ISSUE THREAD

**Issue by first999** [stormrage-project/stormrage-1.12-bugtracker#225]
Hello

There's a problem with learning Swordsmithing. I have done Weaponsmithing quest and when I got to 250 skill points of BS, I took quest "Curruption" from NPC in Everlook (http://www.wowwiki.com/Quest:Corruption), which should give me Sworsmithing skill after completing (that's how soruce's said it should be). 
But when I completed the quest I did not learn the Swordsmithing skill. I can still talk with the NPC (Seril Scourgebane, Everlook - http://www.wowwiki.com/Seril_Scourgebane) and click on the "Train me Swordsmithing" bubble, but that doesn't do anything as well.
So, I have done everything that I think I could and should, but still didn't learn Sworsmithing - I can't learn from recipes that require it.

Best regards

**Comment by cabfever** [comment]
Fixed.
