### ISSUE TITLE
Reckoning talent.

### ISSUE THREAD

**Issue by gojiragwar** [stormrage-project/stormrage-1.12-bugtracker#226]
Reckoning protection talent doesn't work properly.
It only stacks 1 times after receiving a critical hit, It should stack on a maximum of 4.
And actually some talents linked to crits aren't working properly, like "redoubt" for paladins and "enrage"/"blood craze" for warriors, sometimes after a crit they don't even proc.

**Comment by gojiragwar** [comment]
Also wanted to notice you that hunter's pet are quite OP, they doing ton of damage.
I don't remember that in past vanilla, Narci and Teila pets are doing around 170-200 a hit while i'm 7000 armor +,less than 2 second attack, and a lot lot of crits.Plus Both players aren't beast spec....
Maybe pets are bugged.

**Comment by Imabe** [comment]
I was just wondering if any progress has been made with the Reckoning talent or not?

**Comment by stormrage-project** [comment]
Hello gojiragwar,
what exactly is not working properly on redoubt, enrage and blood craze?

**Comment by Imabe** [comment]
I do belive this is the paladin that "left/banned" but I have not seen a problem with Blood Craze and Enrage, and I have a 60 warrior. I am not sure about Redoubt though. but I do know that reckoning isnt stacking :D

**Comment by stormrage-project** [comment]
Fixed.
