### ISSUE TITLE
Quest for Berserker Stance.

### ISSUE THREAD

**Issue by Kuzmin1994** [stormrage-project/stormrage-1.12-bugtracker#228]
Quest The Affray dont work. Tried four times. After the assassination Big Will i have this in my quest log: 
Big Will slain 1/1 
Step on the grate to begin the Affray 0/1

**Comment by Imabe** [comment]
I had no problem getting tis quest on my warrior and doing it.

**Comment by stormrage-project** [comment]
Fixed.
