### ISSUE TITLE
Chamber of Battle in Gemstones in Lower Blackrock Spire is spawned with UBRS Mobs.

### ISSUE THREAD

**Issue by AdmiralAwsum** [stormrage-project/stormrage-1.12-bugtracker#43]
The Chamber of Battles (Room of Overlord Wyrmthalak) in Lower Blackrock Spire are spawned with Upper Blackrock Spire mobs like Chromatic Dragonspawn (15k HP) or Chromatic Whelps that are spawning out of the eggs in UBRS.

**Comment by stormrage-project** [comment]
Fixed.
