### ISSUE TITLE
1 hp death bug

### ISSUE THREAD

**Issue by Fatalsquiddie** [stormrage-project/stormrage-1.12-bugtracker#59]
Sometimes when you die you get stuck on 1 HP and you don't technically die You are alive
but stuck in the same location If you log out and log in it messes up your instances leaving you to have to exit the instance then enter and then leave then enter again on top of that you can be healed but not ressurected and you cannot move

**Comment by stormrage-project** [comment]
Fixed Last Stand as well as Spirit of Redemption.
