### ISSUE TITLE
Devilsaur Skinning

### ISSUE THREAD

**Issue by Fatalsquiddie** [stormrage-project/stormrage-1.12-bugtracker#95]
Myself and critorris were killing Devilsaurs, Ironhide Devilsaurs and Tyrant Devilsaurs on the pretence of getting Devilsaur leather only a few times they weren't giving leather i checked on http://db.vanillagaming.org/?item=15417#skinned-from and its 100% skin rate so it must be bugged

**Comment by stormrage-project** [comment]
Fixed.
